name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-test-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: pip
        cache-dependency-path: requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install pytest

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: python -m pytest -v

    # --- SAST: Semgrep ---
    - name: Semgrep SAST
      uses: returntocorp/semgrep-action@v1
      with:
        config: p/owasp-top-ten
      env:
        SEMGREP_DISABLE_TELEMETRY: "1"

    # --- Dependency scan: pip-audit ---
    - name: Install pip-audit
      run: python -m pip install pip-audit
    - name: Run pip-audit (fail on vulns)
      run: pip-audit --strict

    # --- Container/FS scan: Trivy (filesystem) ---
    - name: Trivy filesystem scan
      uses: aquasecurity/trivy-action@0.24.0
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table'
        severity: 'HIGH,CRITICAL'
        exit-code: '1'   # failaa jos löytyy High/Critical